services:
  webapp:
    container_name: webapp
    build: 
      context: ./WebApp
      dockerfile: webapp.Dockerfile
    image: ihnatiuk/libria-webapp
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
      - type: bind
        source: ~/libria/config
        target: /app/config
    ports:
      - "5000:80"
    depends_on:
      - "flask"
    environment:
      - LIBRIA_SECRETS_PATH=/app/config/
  flask:
    container_name: flask
    build:
      context: ./Flask
      dockerfile: flask.Dockerfile
    image: ihnatiuk/libria-flask
    ports:
      - "7007:7007"
    environment:
      - FLASK_ENV=development
      - SECRETS=/app/config
    volumes:
      - type: bind
        source: ~/libria/config
        target: /app/config
volumes:
  data-protection:
    